### ISSUE TITLE
No way to publish external link content

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#211]
It's also not showing up in the related content field.

**Comment by imperator99** [comment]
I've added the external link content type to the workflow system (in https://github.com/govau/dta-website-rebuild/pull/213).

Unpublished content will not appear in the list for authors because it requires a rather powerful permission. You need to ensure that external links are published before trying to add them to the list. External links are only displayed on these pages so they will be effectively invisible (afterhttps://github.com/govau/dta-website-rebuild/issues/212) until the page they are referenced from is published.
