### ISSUE TITLE
Consider judicious use of `rebuild-cache`

### ISSUE THREAD

**Issue by aeijdenberg** [govau/dta-website-rebuild#443]
Invocations of `rebuild-cache` from any instance appears to prevent serving of traffic by all instances, suggesting that it is putting a global lock on the database.

If this is then case, then perhaps it only needs to be run from a single instance (0) and not all?

We tried this in this commit: https://github.com/govau/dta-website-rebuild/commit/40a6267765008e5afd7a4a604c1a69a0a800e29e

Evaluate whether this change is safe, or whether it should be rolled back.

**Comment by imperator99** [comment]
@aeijdenberg I wonder if perhaps we can limit the use of `drush cache-rebuild` to circumstances when it is genuinely required, for example a module or theme update (as tracked by a change to `composer.json`)? While my experience as a Drupal developer would say that you should clear caches at any given opportunity, perhaps this is no longer really required - especially since any problems which cache-clearing would normally resolve should not make it up into production anyway. And if it did, the cache can still be manually cleared if required.

**Comment by imperator99** [comment]
Resolve by https://github.com/govau/dta-website-rebuild/pull/449.
