### ISSUE TITLE
Cards displaying oddly

### ISSUE THREAD

**Issue by Sarah-Cr** [govau/dta-website-rebuild#587]
Cards at the bottom of https://www.dta.gov.au/about-us are displaying oddly.

![cards displaying oddly](https://user-images.githubusercontent.com/25679296/48747094-344de500-ecc6-11e8-98ca-63165ab9afec.JPG)

**Comment by imperator99** [comment]
@Sarah-Cr this is because the two sets of cards are two different widgets. The first is the menu structure underneath the about us page. The second set are the related content. I don't currently have a good way of merging the two (it may not be possible), however it would make more sense if you inserted a heading between the two, which can be done using the 'Related content heading' field. This could be as simple as 'Related pages' but it is designed so you can use whatever text you like.
