### ISSUE TITLE
Update "Get in touch" module 

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#97]
Title for module should be changed to "Get in touch" 

Add padding before contact module.

Change configuration of module to be free text. Because we need to have different wording for different page contexts. 

![screen shot 2018-03-01 at 11 22 43 am](https://user-images.githubusercontent.com/21048750/36820627-e1c5074e-1d42-11e8-8e7b-bbc13f60d5d9.png)

**Comment by imperator99** [comment]
@NoniH do you just want another field on content types for this? And the heading is always 'Get in touch'?

**Comment by NoniH** [comment]
No because we need to be able to edit it centrally if an email or phone number changes

**Comment by imperator99** [comment]
Okay so to confirm - as the site currently is (due to an update I just pushed) you can use the 'Description' field of the 'Contact' taxonomy term to freely add text however you want, whether it is a phone number or an email address or both. So you can decide on any text you want within the context of the taxonomy, but not the page - so everything with the contact as 'recruitment' will pull the same text. This allows you to change the email or phone number site wide. Is this acceptable? If not, it will take some more thinking and development to figure it out.

**Comment by NoniH** [comment]
Yes I think this will work for now. I'll have a play

**Comment by imperator99** [comment]
Okay will close this for now, please reopen if you need changes made.

Resolved by https://github.com/govau/dta-website-rebuild/pull/111.
